### Generate JWT token
POST http://localhost:8080/token
Content-Type: application/json
Authorization: Basic dnunez pass

### Access home endpoint
GET http://localhost:8080/
#Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZG51bmV6IiwiZXhwIjoxNjc1MDEzODU1LCJpYXQiOjE2NzUwMTAyNTUsInNjb3BlIjoicmVhZCJ9.IjIAtZ8X4_tB2kflUWAmJNTbieeIov1wruohSmVvBE_vBVe7atJP7sSaBKPegtOMxyVDvRlZobG8j7CtfVOvtBffZYGiNcACTHySyHpd9-J10rNcnSqLmjWHdQAaSvBTowQyjJQmGPZbJJUeMJ0hnXSGjF8PQd07tjoVXZDqFhAMWTrwzdHKmr5jf-L5vffSmFCsrigwnSCMbbrnT0O3roLaB6OSH8TedUFwrkxQ0ZmTRsb8CqGgRJpT4kTmjZWzqxCRy-8YoCrcbjSwKEuUbDHfmmsjQZv7uGkNbe7ttOe9HSyXrDZ9uAfpv2pfRYxYplAMclOt8JLM3AK1QJEQ7Q
Authorization: Basic dnunez pass

### Generate JWT token
POST http://localhost:8080/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZG51bmV6IiwiZXhwIjoxNjc1MDEzODU1LCJpYXQiOjE2NzUwMTAyNTUsInNjb3BlIjoicmVhZCJ9.IjIAtZ8X4_tB2kflUWAmJNTbieeIov1wruohSmVvBE_vBVe7atJP7sSaBKPegtOMxyVDvRlZobG8j7CtfVOvtBffZYGiNcACTHySyHpd9-J10rNcnSqLmjWHdQAaSvBTowQyjJQmGPZbJJUeMJ0hnXSGjF8PQd07tjoVXZDqFhAMWTrwzdHKmr5jf-L5vffSmFCsrigwnSCMbbrnT0O3roLaB6OSH8TedUFwrkxQ0ZmTRsb8CqGgRJpT4kTmjZWzqxCRy-8YoCrcbjSwKEuUbDHfmmsjQZv7uGkNbe7ttOe9HSyXrDZ9uAfpv2pfRYxYplAMclOt8JLM3AK1QJEQ7Q

