### Generate JWT token
POST http://localhost:8080/token
Content-Type: application/json
Authorization: Basic dnunez pass

{
  "username": "dnunez",
  "password": "pass"
}

### Access home endpoint
GET http://localhost:8080/
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZG51bmV6IiwiZXhwIjoxNjc1MDE3NTEyLCJpYXQiOjE2NzUwMTM5MTIsInNjb3BlIjoicmVhZCJ9.oul6NJdMBip47KZfNx8MWDOIFnNbR0y4Q2EatiZN_Z6b062bYylccasLOpozXFYALvphsKmSV6KAX_Pb4GaFCb5IxDaFrXkCroeBqRqkQXIih1uVrnZ2OEAolIQ_4kgEW-jv8cLt_Na6dUJMsHXbQ1eLz5PmGjSQp2uXgVq-7DK3u0VKBKlKQochuWE6x-dsyfIt-ITMgBQx1QRNUk-6kc0OgwSjBGS5QHfgdE7zhozax9Wj6gdA8QFfO6E270pxVsGJTsiKvhoSS_ICkNKJPMey28DRb4hw6Skj-QX6OmWGeWAp-lxBteMWVRVswEKcUbfugdNRaML9CH58TtEPBA


### Access secured endpoint read authority
GET http://localhost:8080/secured-read
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZG51bmV6IiwiZXhwIjoxNjc1MDE3NTEyLCJpYXQiOjE2NzUwMTM5MTIsInNjb3BlIjoicmVhZCJ9.oul6NJdMBip47KZfNx8MWDOIFnNbR0y4Q2EatiZN_Z6b062bYylccasLOpozXFYALvphsKmSV6KAX_Pb4GaFCb5IxDaFrXkCroeBqRqkQXIih1uVrnZ2OEAolIQ_4kgEW-jv8cLt_Na6dUJMsHXbQ1eLz5PmGjSQp2uXgVq-7DK3u0VKBKlKQochuWE6x-dsyfIt-ITMgBQx1QRNUk-6kc0OgwSjBGS5QHfgdE7zhozax9Wj6gdA8QFfO6E270pxVsGJTsiKvhoSS_ICkNKJPMey28DRb4hw6Skj-QX6OmWGeWAp-lxBteMWVRVswEKcUbfugdNRaML9CH58TtEPBA

### Access secured endpoint write authority
GET http://localhost:8080/secured-write
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZG51bmV6IiwiZXhwIjoxNjc1MDE3NTEyLCJpYXQiOjE2NzUwMTM5MTIsInNjb3BlIjoicmVhZCJ9.oul6NJdMBip47KZfNx8MWDOIFnNbR0y4Q2EatiZN_Z6b062bYylccasLOpozXFYALvphsKmSV6KAX_Pb4GaFCb5IxDaFrXkCroeBqRqkQXIih1uVrnZ2OEAolIQ_4kgEW-jv8cLt_Na6dUJMsHXbQ1eLz5PmGjSQp2uXgVq-7DK3u0VKBKlKQochuWE6x-dsyfIt-ITMgBQx1QRNUk-6kc0OgwSjBGS5QHfgdE7zhozax9Wj6gdA8QFfO6E270pxVsGJTsiKvhoSS_ICkNKJPMey28DRb4hw6Skj-QX6OmWGeWAp-lxBteMWVRVswEKcUbfugdNRaML9CH58TtEPBA

